apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2-route
spec:
  selector:
    matchLabels:
      app: api2-route
  replicas: 1
  template:
    metadata:
      labels:
        app: api2-route
      annotations:
        timestamp: "{{ now }}"        
    spec:
      containers:
        - name: api2-route
          image: api2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000